openapi: 3.0.1
info:
  title: will be replaced
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1
paths:
  /agencies:
    get:
      tags:
        - agency-controller
      summary: 'Returns a randomly sorted list of agencies. If no agency is found the white spot
        agency id is being returned. When no white spot agency is defined No Content
        is being returned. [Authorization: none]'
      operationId: getAgencies
      parameters:
        - name: postcode
          in: query
          required: true
          description: The postcode the user entered
          schema:
            type: string
            minLength: 5
            maxLength: 5
            example: "56789"
        - name: consultingType
          in: query
          required: true
          description: The consulting type of the registration form
          schema:
            type: integer
            format: int32
            example: 5
        - name: topicId
          in: query
          required: false
          description: The main topic of the registration form
          schema:
            type: integer
            format: int32
            example: 7
        - name: age
          in: query
          required: false
          description: Age from the registration form
          schema:
            type: integer
            format: int32
            example: 27
        - name: gender
          in: query
          required: false
          description: Gender from the registration form
          schema:
            type: string
            example: "FEMALE"
      responses:
        200:
          description: OK - successfull operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FullAgencyResponseDTO'
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        403:
          description: FORBIDDEN - no/invalid CSRF token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
  /agencies/{agencyIds}:
    get:
      tags:
        - agency-controller
      summary: 'Returns the information of provided agencies (Ids). [Authorization: none]'
      operationId: getAgenciesByIds
      parameters:
        - name: agencyIds
          in: path
          description: List of comma-seperated Agency IDs
          required: true
          style: simple
          explode: false
          schema:
            type: array
            items:
              type: integer
              format: int64
              example: 20
      responses:
        200:
          description: OK - successfull operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AgencyResponseDTO'
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        403:
          description: FORBIDDEN - no/invalid CSRF token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
  /agencies/consultingtype/{consultingTypeId}:
    get:
      tags:
        - agency-controller
      summary: 'Returns all agencies for provided consulting type. [Authorization: none]'
      operationId: getAgenciesByConsultingType
      parameters:
        - name: consultingTypeId
          in: path
          description: the consulting type id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK - successfull operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AgencyResponseDTO'
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        403:
          description: FORBIDDEN - no/invalid CSRF token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition

components:
  schemas:
    AgencyResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 684
        name:
          type: string
          example: "Suchtberatung Freiburg"
        postcode:
          type: string
          example: "79106"
        city:
          type: string
          example: "Bonn"
        description:
          type: string
          example: "Our agency provides help for the following topics: Lorem ipsum.."
        teamAgency:
          type: boolean
          example: "false"
        offline:
          type: boolean
          example: "false"
        consultingType:
          type: integer
          example: 0
        tenantId:
          type: integer
          format: int64
          example: 12
        topicIds:
          type: array
          items:
            type: long

    FullAgencyResponseDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/AgencyResponseDTO'
        - type: object
          properties:
            demographics:
              $ref: '#/components/schemas/DemographicsDTO'
            url:
              type: string
              example: http://www.domain.com/agency
            external:
              type: boolean
              example: "false"

    DemographicsDTO:
      type: object
      properties:
        ageFrom:
          type: integer
          minimum: 0
          maximum: 200
          example: 25
        ageTo:
          type: integer
          minimum: 0
          maximum: 200
          example: 55
        genders:
          type: array
          items:
            type: string
          example: "[MALE,FEMALE,DIVERS]"
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
