openapi: 3.0.1

info:
  title: will be replaced
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1

servers:
  - url: /

paths:
  /liveevent/send:
    post:
      tags:
        - live-controller
      summary: Send events via the live service
      operationId: sendLiveEvent
      parameters:
        - name: userIds
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/LiveEventMessage'
      responses:
        200:
          description: OK - successfull operation
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition

components:
  schemas:
    LiveEventMessage:
      type: object
      required:
        - eventType
      properties:
        eventType:
          $ref: '#/components/schemas/EventType'
        eventContent:
          $ref: '#/components/schemas/EventContent'

    EventType:
      type: string
      enum:
        - "directMessage"
        - "videoCallRequest"
        - "videoCallDeny"

    EventContent:
      description: general used object for all possible incoming DTOs used for socket transfer
      type:
        object

    VideoCallRequestDTO:
      description: the request DTO for event type videoCallRequest
      type: object
      required:
        - videoCallUrl
        - username
        - rcRoomId
      properties:
        videoCallUrl:
          type: string
          example: video.domain.com/44c7644a-5977-11eb-ae93-0242ac130002
          description: The url of the video server
        username:
          type: string
          example: consultant
          description: The username of the calling user
        rcUserId:
          type: string
          example: "ag89h3tjkerg94t"
          description: The Rocket.Chat user id of calling user
        rcGroupId:
          type: string
          example: "xGklslk2JJKK"
          description: The Rocket.Chat room id of the session
