openapi: 3.0.1

info:
  title: will be replaced
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1

paths:
  /liveevent/send:
    post:
      tags:
        - live-controller
      summary: Send events via the live service
      operationId: sendLiveEvent
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/LiveEventMessage'
      responses:
        200:
          description: OK - successfull operation
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition

components:
  schemas:
    LiveEventMessage:
      type: object
      required:
        - eventType
        - userIds
      properties:
        eventType:
          $ref: '#/components/schemas/EventType'
        userIds:
          type: array
          items:
            type: string
        eventContent:
          $ref: '#/components/schemas/EventContent'

    EventType:
      type: string
      enum:
        - "anonymousEnquiryAccepted"
        - "anonymousConversationFinished"
        - "directMessage"
        - "newAnonymousEnquiry"
        - "videoCallRequest"
        - "videoCallDeny"

    StatusSource:
      type: object
      required:
        - finishConversationPhase
      properties:
        finishConversationPhase:
          type: string
          description: "represents the session status of the anonymous conversation where the
          anonymousConversationFinished event has been triggered"
          enum:
            - "NEW"
            - "IN_PROGRESS"

    EventContent:
      description: general used object for all possible incoming DTOs used for socket transfer
      type:
        object

    VideoCallRequestDTO:
      description: the request DTO for event type videoCallRequest
      type: object
      required:
        - videoCallUrl
        - initiatorUsername
        - initiatorRcUserId
        - rcGroupId
      properties:
        videoCallUrl:
          type: string
          example: video.domain.com/44c7644a-5977-11eb-ae93-0242ac130002
          description: The url of the video server
        initiatorUsername:
          type: string
          example: consultant
          description: The username of the calling user
        initiatorRcUserId:
          type: string
          example: "ag89h3tjkerg94t"
          description: The Rocket.Chat user id of the calling user
        rcGroupId:
          type: string
          example: "xGklslk2JJKK"
          description: The Rocket.Chat room id of the session
